title: Rtr. Rtn. Arun Teja Godavarthi
username: Rtr. Rtn. Arun Teja Godavarthi
description: Brief timeline of Rtr. Rtn. Arun Teja Godavarthi's Rotaract journey.

# /assets/....
og_img: /assets/images/zeospec.jpg

# typing_text: This will be typed before 'scroll down for more'.
# > set this to your job/role title
typing_text: DRS Operations & Training

email: hi@zeospec.com
# github_username: ZeoSpec
# codepen_username: exampleUser
# dev_username: exampleUser
linkedin_username: ZeoSpec
twitter_username: ZeoSpec
facebook_username: ZeoSpec
instagram_username: ZeoSpec

# ABOUT ME SECTION
show_aboutme_card: true
about_me_title: About Me
# about_me_description: This will be displayed under the title. <a class="highlight-link" href="https://github.com/zeospec" target="_blank" rel="noreferrer"> Github </a>
about_me_description: I entered the Rotary-Rotaract family as a Rotaractor in 2015 through Rotaract Club of CMRIT. It all began with RotaFest 2K15, I consider it fortunate to have been inducted into Rotaract by PDRR Rtr. Manohar H M. 29 August 2020 marked another beginning when PDG Rtn. S R Yogananda pinned the Rotary wheel to my Jacket. Rotary & Rotaract Bangalore East are my homes in the Rotary world.

# SKILLS SECTION
show_skills_card: false
# skills_title: Skills
skills_title: AAAAAAAA

# TIMELINE SECTION
show_timeline_card: true
timeline_title: Brief Rotaract Timeline 

cv_download_link: https://zeospec.com/

# PROJECTS SECTION

show_projects_card: false
show_projects: true
projects_title: Caaaming Sooonn!!!
# projects_title: Key Initiatives/Works
show_os_projects: false
os_projects_title: Open Source Projects

# projects_title: Subscriber Section
show_google_form_subscription: true
google_form: https://docs.google.com/forms/d/e/1FAIpQLSfB3qsTYxgAcWdde5Jzq7JquR2ASwVR9myv9dy3ULH7UOM2vg/formResponse
formNamekey: entry.6950510
formEmailkey: entry.1470521357

# CONTACT SECTION
show_contact_card: true
contact_title: Contact
contact_description: Have a question or want to chat? Pick up your phone and dial up or connect over social media. Also, jump on to my <a class="highlight-link" href="https://zeospec.com" target="_blank" rel="noreferrer">blog</a>.

# GOOGLE-ANALYTICS
google-analytics:
  id: "UA-172399613-2"

